import React, { Fragment } from "react";
import Head from "next/head";

const Ranks = () => {
    return (
        <Fragment>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>ranks</h1>
        </Fragment>
    );
};

export default Ranks;
