import Head from "next/head";
import { useSelector } from "react-redux";
import styled from "styled-components";
import { ThemeProvider } from "styled-components";
import Layout from "../components/Layout/Layout";
import { darkTheme, lightTheme } from "../styles/theme";
import { GlobalStyles } from "./../styles/globalStyles";

const Home = () => {
    const { theme } = useSelector((state) => state.ui);
    const currentTheme = theme === "light" ? lightTheme : darkTheme;

    return (
        <ThemeProvider theme={currentTheme}>
            <GlobalStyles />
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <h1>hi</h1>
            </Layout>
        </ThemeProvider>
    );
};

const Title = styled.h1``;

export default Home;
